### ISSUE TITLE
Add to pecl install for PHP?

### ISSUE THREAD

**Issue by mkormendy** [maxmind/libmaxminddb#226] opened 2020-04-15 18:41 UTC
It would seem that this would be something trivial to add to the PECL database online to assist with easy installation as a PHP .so file.

**Comment by oschwald** [comment] 2020-04-15 18:48
This is a dupe of https://github.com/maxmind/MaxMind-DB-Reader-php/issues/34.

**Closed by oschwald** 2020-04-15 18:48 UTC
