### ISSUE TITLE
C++ "const" warning

### ISSUE THREAD

**Issue by davidbenoit** [maxmind/libmaxminddb#126] opened 2016-10-09 06:43 UTC
The following error is emitted when part of a C++ project using a member data handle to MMDB_s in a const method.

```
maxmind/maxminddb.h:195:33: note: initializing argument 1 of ‘MMDB_lookup_result_s MMDB_lookup_string(MMDB_s*, const 
   char*, int*, int*)’
     extern MMDB_lookup_result_s MMDB_lookup_string(MMDB_s *const mmdb,
```

The workaround in C++ is to use `const_cast`, but those should only be used if the source can't be updated.  Please add appropriate const tagging if a C++ compiler is detected.

**Comment by autarch** [comment] 2016-10-10 16:28
Hi David,

None of us are terribly familiar with C++. Could you elaborate on what you're asking us to change? Of course, a PR would be event better ;)

**Comment by oschwald** [comment] 2018-02-23 23:11
I am closing this due to lack of information about how to reproduce the warnings.

**Closed by oschwald** 2018-02-23 23:11 UTC
